pcparts_store/main/urls.py
from django.urls import path

from pcparts_store.main.views import ItemListView, CheckoutView, ItemDetailsView, add_to_cart, remove_from_cart, \
    CartView, PaymentView

urlpatterns = [
    path('', ItemListView.as_view(), name='home-page'),
    path('checkout', CheckoutView.as_view(), name='checkout-page'),
    path('product/<int:pk>', ItemDetailsView.as_view(), name='product-page'),
    path('add-to-cart/<int:pk>', add_to_cart, name='add-to-cart-page'),
    path('remove-from-cart/<int:pk>', remove_from_cart, name='remove-from-cart-page'),
    path('cart/', CartView.as_view(), name='cart-page'),
    path('payment/<payment_option>', PaymentView.as_view(), name='payment-page'),
]

pcparts_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pcparts_store.main.urls')),
                  path('accounts/', include('pcparts_store.accounts.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pcparts_store/main/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django_countries.fields import CountryField

# Create your models here.

CATEGORY_CHOICES = (
    ('OTHER', 'Other'),
    ('CPU', 'CPU'),
    ('GPU', 'GPU'),
    ('RAM', 'RAM'),
    ('MB', 'Motherboard'),
    ('SSD', 'Solid State Drive'),
    ('HDD', 'Hard Disk Drive'),
    ('PSU', 'Power Supply Unit'),
    ('CPU-COOLER', 'Cpu Cooler'),
    ('CASE', 'Case'),
)

LABEL_CHOICES = (
    ('PR', 'primary'),
    ("SC", 'secondary'),
    ('DR', 'danger'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=100, default=CATEGORY_CHOICES[0][0])
    label = models.CharField(choices=LABEL_CHOICES, max_length=2, default=LABEL_CHOICES[0][0])
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def get_add_to_cart_url(self):
        return reverse('add-to-cart', kwargs={'pk': self.pk})

    def get_label_text(self):
        if self.label == 'PR':
            return 'NEW'
        elif self.label == 'DR':
            return 'SALE'
        else:
            return ''

    def __str__(self):
        return self.title


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, null=True, blank=True)

    def get_total_price(self):
        return self.quantity * self.item.price

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def get_total_price(self):
        price = 0
        for item in self.items.all():
            price += item.get_total_price()
        return price

    def __str__(self):
        return str(self.user)

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zipcode = models.CharField(max_length=10)

    def __str__(self):
        return str(self.user)

pcparts_store/main/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal'),
)

class CheckoutForm(forms.Form):
    street_address = forms.CharField(label='Street Address', max_length=100, widget=forms.TextInput(attrs={'placeholder': '1234 Main St.'}))
    apartment_address = forms.CharField(label='Apartment Address', max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Apartment or Suite'}))
    country = CountryField(blank_label='Select Country').formfield(
        widget=CountrySelectWidget(attrs={'class': 'form-control'})
    )
    zip = forms.CharField(label='Zip Code', max_length=10)
    same_billing_address = forms.BooleanField(label='Same Billing Address', widget=forms.CheckboxInput, required=False)
    save_info = forms.BooleanField(label='Save Info', widget=forms.CheckboxInput, required=False)
    payment_options = forms.ChoiceField(label='Payment Options', widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

pcparts_store/main/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic as views

from pcparts_store.main.forms import CheckoutForm
from pcparts_store.main.models import Item, OrderItem, Order, BillingAddress


# Create your views here.
class ItemListView(views.ListView):
    model = Item
    context_object_name = 'items'
    paginate_by = 8
    template_name = 'main/home-page.html'


class ItemDetailsView(views.DetailView):
    model = Item
    context_object_name = 'item'
    template_name = 'main/product-page.html'


class CartView(views.View):
    def get(self, request):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            return render(self.request, 'main/cart-page.html', {'order': order})
        except ObjectDoesNotExist:
            messages.error(self.request, 'Order does not exist')
            return redirect('home-page')


def add_to_cart(request, pk):
    redirect_url = request.GET.get('redirect_url', 'product-page')
    item = get_object_or_404(Item, pk=pk)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=pk).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'Item quantity updated.')
        else:
            messages.info(request, 'Item added to cart.')
            order.items.add(order_item)
    else:
        order_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=order_date)
        order.items.add(item)
        messages.info(request, 'Item added to cart.')
    return redirect(redirect_url, pk=pk)


def remove_from_cart(request, pk):
    redirect_url = request.GET.get('redirect_url', 'product-page')
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=pk).exists():
            order_item = OrderItem.objects.get(item=item, user=request.user, ordered=False)
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, 'Item removed from the cart.')
        else:
            messages.info(request, 'Item was not in the cart.')
    else:
        messages.info(request, 'You do not have an active order.')
    return redirect(redirect_url, pk=pk)


class CheckoutView(views.View):
    def get(self, request):
        form = CheckoutForm()
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            return render(self.request, 'main/checkout-page.html', {
                'form': form,
                'order': order,
            })
        except ObjectDoesNotExist:
            messages.error(self.request, 'Order does not exist')
            return redirect('home-page')

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zipcode = form.cleaned_data.get('zip')
                # TODO
                # same_billing_address = form.cleaned_data.get('same_billing_address')
                # save_info = form.cleaned_data.get('save_info')
                payment_options = form.cleaned_data.get('payment_options')
                billing_address = BillingAddress(
                    user=self.request.user,
                    street=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    zipcode=zipcode,
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                print(payment_options)
                return redirect('payment-page', payment_option=payment_options)
            messages.warning(self.request, 'Checkout form submission failed.')
            return redirect('checkout-page')
        except ObjectDoesNotExist:
            messages.error(self.request, 'Order does not exist')
            return redirect('cart-page')

class PaymentView(views.View):
    def get(self, *args, **kwargs):
        return render(self.request, 'main/payment-page.html')

templates/main/cart-page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="d-flex justify-content-center">
            <div class="table-responsive w-100">
                <table class="table text-center w-100">
                    <thead>
                        <tr>
                            <th scope="col" style="width: 10%;">Item ID</th>
                            <th scope="col" style="width: 40%;">Item Title</th>
                            <th scope="col" style="width: 15%;">Price</th>
                            <th scope="col" style="width: 15%;">Quantity</th>
                            <th scope="col" style="width: 20%;">Total Item Price</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider table-divider-color">
                        {% for order_item in order.items.all %}
                            <tr>
                                <td>{{ order_item.item.pk }}</td>
                                <td>{{ order_item.item.title }}</td>
                                <td>${{ order_item.item.price }}</td>
                                <td>
                                    <a href="{% url 'remove-from-cart-page' pk=order_item.item.pk %}?redirect_url={{ request.path }}"
                                       class="fas fa-minus"> </a>
                                    {{ order_item.quantity }}
                                    <a href="{% url 'add-to-cart-page' pk=order_item.item.pk %}?redirect_url={{ request.path }}"
                                       class="fas fa-plus"></a>
                                </td>
                                <td>${{ order_item.get_total_price }}</td>
                            </tr>
                        {% endfor %}
                        <!-- Order Total Row -->
                        <tr>
                            <td><b>Order Total</b></td>
                            <td colspan="3"></td>
                            <td><b>${{ order.get_total_price }}</b></td>
                        </tr>
                        <!-- Checkout Button Row -->
                        <tr>
                            <td colspan="4"></td>
                            <td>
                                <a href="{% url 'checkout-page' %}" class="btn btn-outline-dark btn-sm">Checkout</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/checkout-page.html
{% extends 'base.html' %}
{% block content %}


    <!--Main layout-->
    <main>
        <div class="container">
            <!-- Heading -->
            <h2 class="my-5 text-center">Checkout form</h2>

            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-md-8 mb-4">
                    <!--Card-->
                    <div class="card p-4">
                        <form method="POST">
                            {% csrf_token %}
                            <!--address-->
                            <p class="mb-0">
                                Address
                            </p>
                            <div class="form-outline mb-4">
                                {{ form.street_address }}
                            </div>

                            <!--address-2-->
                            <p class="mb-0">
                                Address 2 (optional)
                            </p>
                            <div class="form-outline mb-4">
                                {{ form.apartment_address }}
                            </div>

                            <!--Grid row-->
                            <div class="row">
                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 ">
                                    <p class="mb-0">
                                        Country
                                    </p>
                                    <div class="form-outline">
                                        {{ form.country }}
                                    </div>
                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-12 ">
                                    <p class="mb-0">
                                        Zip
                                    </p>
                                    <div class="form-outline">
                                        {{ form.zip }}
                                    </div>
                                </div>
                                <!--Grid column-->
                            </div>
                            <!--Grid row-->

{#                            <hr/>#}
{#                            <div class="form-check">#}
{#                                {{ form.same_billing_address }}#}
{#                                <label class="form-check-label" for="flexCheckDefault">Shipping address is the same as#}
{#                                    my#}
{#                                    billing address</label>#}
{#                            </div>#}
{##}
{#                            <div class="form-check">#}
{#                                {{ form.save_info }}#}
{#                                <label class="form-check-label" for="flexCheckDefault">Save this information for next#}
{#                                    time</label>#}
{#                            </div>#}
{##}
{#                            <hr/>#}

                            <div class="my-3">
                                <p class="mb-0">Payment Options</p>
                                <div class="form-check px-0">
                                    {{ form.payment_options }}
                                </div>
                            </div>
                            <hr class="mb-4"/>
                            <button class="btn btn-primary" type="submit">Continue to checkout</button>
                        </form>
                    </div>
                    <!--/.Card-->
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-4">
                    <!-- Heading -->
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
{#                        <span class="badge rounded-pill badge-primary">{{ order.items.count }}</span>#}
                    </h4>

                    <!-- Cart -->
                    <ul class="list-group mb-3">
                        {% for order_item in order.items.all %}
                            <li class="list-group-item d-flex justify-content-between">
                                <div>
                                    <h6 class="my-0">{{ order_item.item.title }}</h6>
                                    <small class="text-muted">Quantity: {{ order_item.quantity }}</small>
                                </div>
                                <span class="text-muted">${{ order_item.get_total_price }}</span>
                            </li>
                        {% endfor %}

                        <li class="list-group-item d-flex justify-content-between">
                            <span style="font-weight: 500">Total (USD)</span>
                            <span style="font-weight: 500">${{ order.get_total_price }}</span>
                        </li>
                    </ul>
                    <!-- Cart -->
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </div>
    </main>
    <!--Main layout-->
{% endblock %}

templates/main/home-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--Main layout-->
    <main class="d-flex flex-column">
        <div class="container">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
                <!-- Container wrapper -->
                <div class="container-fluid">

                    <!-- Navbar brand -->
                    <a class="navbar-brand">Categories:</a>

                    <!-- Toggle button -->
                    <button
                            class="navbar-toggler"
                            type="button"
                            data-mdb-toggle="collapse"
                            data-mdb-target="#navbarSupportedContent2"
                            aria-controls="navbarSupportedContent2"
                            aria-expanded="false"
                            aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>

                    <!-- Collapsible wrapper -->
                    <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                        <!-- TODO -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <!-- Link -->
                            <li class="nav-item acitve">
                                <a class="nav-link text-white" href="#">All</a>
                            </li>
                            {#                            <li class="nav-item">#}
                            {#                                <a class="nav-link text-white" href="#">Components</a>#}
                            {#                            </li>#}
                        </ul>

                        <!-- TODO -->
                        <!-- Search -->
                        <form class="w-auto py-1" style="max-width: 12rem">
                            <input type="search" class="form-control rounded-0" placeholder="Search"
                                   aria-label="Search">
                        </form>

                    </div>
                </div>
                <!-- Container wrapper -->
            </nav>

            <!-- Products -->
            <section>
                <div class="d-flex flex-wrap justify-content-center text-center gap-4 mt-4">
                    {% for item in items %}
                        <div class="item-box border rounded p-3 d-flex flex-column align-items-center justify-content-between"
                             style="width: 250px; height: 350px;">
                            <!-- Item Image -->
                            <div class="bg-image mb-3 hover-zoom ripple ripple-surface ripple-surface-light"
                                 data-mdb-ripple-color="light"
                                 style="height: 150px; width: 100%; overflow: hidden;"
                                 href="{% url 'product-page' pk=item.pk %}">
                                {% if item.image %}
                                    <img src="{{ item.image.url }}" alt="no-image-available" class="img-fluid"
                                         style="max-height: 100%; max-width: 100%; object-fit: cover;"/>
                                {% else %}
                                    <img src="{% static 'img/default-item-image.jpg' %}" alt="no-image-available"
                                         class="img-fluid"
                                         style="max-height: 100%; max-width: 100%; object-fit: cover;"/>
                                {% endif %}
                                <a href="{% url 'product-page' pk=item.pk %}">
                                    <div class="mask">
                                        <div class="d-flex justify-content-start align-items-end h-100">
                                            <h5><span
                                                    class="badge bg-{{ item.get_label_display }} ms-2 p-1"
                                                    style="font-size: 0.7rem">{{ item.get_label_text }}</span>
                                            </h5>
                                        </div>
                                    </div>
                                    <div class="hover-overlay">
                                        <div class="mask"
                                             style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                    </div>
                                </a>
                            </div>

                            <!-- Item Title -->
                            <a href="{% url 'product-page' pk=item.pk %}" class="text-reset text-decoration-none">
                                <h5 class="card-title mb-2">{{ item.title|truncatechars:40 }}</h5>
                            </a>

                            <!-- Item Category -->
                            <p class="text-muted">{{ item.category }}</p>

                            <!-- Item Price -->
                            <h6 class="mb-3 price">${{ item.price }}</h6>

                            <!-- View Details Button -->
                            <div class="mt-auto">
                                <a href="{% url 'product-page' pk=item.pk %}" class="btn btn-outline-primary btn-sm">
                                    View Details
                                </a>
                            </div>
                        </div>

                    {% empty %}
                        <h1>No items to show at this time.</h1>
                    {% endfor %}
                </div>
            </section>

            <!-- Pagination -->
            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
                <ul class="pagination">
                    <!-- Previous Page -->
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous" tabindex="-1">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    <!-- Page Numbers -->
                    {% for page_num in paginator.page_range %}
                        {% if page_num == page_obj.number %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    <!-- Next Page -->
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Next" tabindex="-1">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </main>
{% endblock %}

templates/main/payment-page.html
{% extends 'base.html' %}

{% block content %}

<h1>TODO: Implement Payment</h1>

{% endblock %}

templates/main/product-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container-fluid px-3 px-md-5">
            <!--Grid row-->
            <div class="row align-items-center">
                <!--Grid column: Product Image-->
                <div class="col-md-6 mb-4 text-center">
                    <div class="image-container"
                         style="width: 100%; max-width: 400px; aspect-ratio: 1 / 1; overflow: hidden; margin: auto; border-radius: 8px; box-shadow: 0 0 10px 1px rgba(0, 0, 0, 0.1);">
                        {% if item.image %}
                            <img src="{{ item.image.url }}"
                                 alt="{{ item.title }}"
                                 class="img-fluid h-100 w-100"
                                 style="object-fit: contain; border-radius: 8px;">
                        {% else %}
                            <img src="{% static 'img/default-item-image.jpg' %}"
                                 alt="No image available"
                                 class="img-fluid h-100 w-100"
                                 style="object-fit: contain; border-radius: 8px;">
                        {% endif %}
                    </div>
                </div>
                <!--Grid column-->

                <!--Grid column: Product Details-->
                <div class="col-md-6 mb-4">
                    <!--Content-->
                    <div class="p-3 p-md-4">
                        <!--Category and Label Badges-->
                        <div class="mb-3">
                            <a href="#">
                                <span class="badge bg-dark me-1">{{ item.category }}</span>
                            </a>
                            {% if item.get_label_display %}
                                <a href="#">
                                    <span class="badge bg-{{ item.get_label_display }} me-1">{{ item.get_label_text }}</span>
                                </a>
                            {% endif %}
                        </div>

                        <!--Title and Price-->
                        <h2 class="mb-3 fw-bold text-center text-md-start">{{ item.title }}</h2>
                        <p class="lead fs-4 text-center text-md-start">
                            <strong>${{ item.price }}</strong>
                        </p>

                        <!--Description-->
                        <div class="mb-4">
                            <h5 class="fw-bold">Description</h5>
                            {% if item.description %}
                                <p>{{ item.description | linebreaks }}</p>
                            {% else %}
                                <p class="text-muted">This item has no description available.</p>
                            {% endif %}
                        </div>

                        <!--Cart Actions-->
                        {% if request.user.is_authenticated %}
                            <div class="d-flex gap-3 justify-content-center justify-content-md-start">
                                <a href="{% url 'add-to-cart-page' pk=item.pk %}" class="btn btn-primary">
                                    Add to Cart
                                    <i class="fas fa-shopping-cart ms-2"></i>
                                </a>
                                <a href="{% url 'remove-from-cart-page' pk=item.pk %}" class="btn btn-danger">
                                    Remove from Cart
                                </a>
                            </div>
                        {% else %}
                            <div class="alert alert-secondary mt-4 text-center text-md-start" style="max-width: 340px">
                                Please <a href="{% url 'login-page' %}" class="alert-link">login</a> to add this item to your
                                cart.
                            </div>
                        {% endif %}
                    </div>
                    <!--Content-->
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->

            <!--Divider-->
            <hr class="my-5"/>
        </div>
    </main>
    <!--Main layout-->

{% endblock %}